// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFrame: typeof import('./src/components/AppFrame.vue')['default']
    ICarbonArrowRight: typeof import('virtual:vite-icons/carbon/arrow-right')['default']
    ICarbonShoppingCart: typeof import('virtual:vite-icons/carbon/shopping-cart')['default']
    ILogosVue: typeof import('virtual:vite-icons/logos/vue')['default']
    NavTop: typeof import('./src/components/NavTop.vue')['default']
  }
}

export { }
